### ISSUE TITLE
Configurando Spring Parte 1

### ISSUE THREAD

**Issue by ivanagermir** [CodeSystem2022/CodeStyle4toSemestre#17]
Cargar archivos trabajados en el video 1, clase 2 de Metodología de Sistemas

**Comment by gabi-silva** [comment]
Hola Ivana, ya realicé la tarea pero no me tocaría subir nada, en el siguiente video de Java se sube la carpeta y creo que le corresponde a otra persona, es así? de ser así quedaría cerrada mi tarea pero sin commit.
Saludos!

**Comment by ivanagermir** [comment]
Perfecto Gabriela, gracias por tu aporte!

**Comment by gabi-silva** [comment]
Cierro tarea!
