### ISSUE TITLE
JAVA - Clase 6 -  Tienda de Libros con SpringBoot y Swing

### ISSUE THREAD

**Issue by Martinv12** [CodeSystem2022/CodeStyle4toSemestre#65]
Sprint Semana 5 - ( Ivana Germir -)

# Java

-6.2 Configuración y descarga del proyecto

-6.3 Abrimos el proyecto y configuramos

   - Parte 1 -> Abrir proyecto

   - Parte 2 -> log-back.xml y commit

   - Parte 3 -> Conexión a la base de datos => Parte 1 y 2

**Comment by ivanagermir** [comment]
Listo, tarea subida
